#!/bin/tcsh
limit stacksize unlimited
cd ~/Dropbox

## Start Amazon Cloud Drive ##
#if (! -d /media/acd/waltz) then
#  echo do acd_cli
#  acd_cli sync
#  acd_cli mount /media/acd
#endif

#### User Settings ####
eval  `dircolors ~/.dir_colors`
alias ls 'ls -GFh --color=auto'
alias ll 'ls -l'
alias la 'ls -a'
alias lla 'ls -la'
alias cp 'cp -p'
alias grep 'grep --color=auto'
alias df 'df -ah'
alias rm 'trash'
alias rmx '/bin/rm'
alias count 'll . | wc -l'
alias alljob 'ps aux | less'

alias ssh 'ssh -Y'
alias scp 'scp -p'
alias bzip2 'bzip2 -9'
alias gzip 'gzip -9 --rsyncable'
alias image 'eog'
alias dirsize "du -h --max-depth=1 "	# followed by the directory name
setenv TERM xterm

## Check CPU stats ##
alias mpstat 'mpstat -P ALL' #Check CPU stat
alias chknodes 'ps -eo pcpu,pid,user,args | sort -k 1 -r |head -10'
alias isostat 'isostat -xtc 5 3'
alias gcpu 'gnome-system-monitor'

alias d 'cd /home/pmung/Dropbox'
alias x 'cd /home/pmung/xxx_data'
setenv D '/home/pmung/Dropbox'
setenv X '/home/pmung/xxx_data'

#### Logging ####
alias mva    'ssh ungp01@chimera.hpc.mssm.edu'
alias rumba  'ssh pmung@rumba.anbg.mssm.edu'	# 10.90.122.117
alias tango  'ssh pmung@tango.anbg.mssm.edu'	# 10.90.121.236
alias ballet 'ssh pmung@ballet.anbg.mssm.edu'	# 10.90.121.167
alias pointe 'ssh pmung@pointe.anbg.mssm.edu'	# 10.90.121.
alias samba  'ssh pmung@samba.anbg.mssm.edu'	# 10.90.121.
alias disco  'ssh pmung@disco.anbg.mssm.edu'
alias jethro 'ssh pmung@jethro.anbg.mssm.edu'	# Marc Birtwistle GPU

alias pils   'ssh pmung@pils-ext.phar.umich.edu'

setenv MVA    'ungp01@chimera.hpc.mssm.edu://hpc/users/ungp01'
setenv MVASCR 'ungp01@chimera.hpc.mssm.edu://sc/hydra/scratch/ungp01'
setenv MVAPJ  'ungp01@chimera.hpc.mssm.edu://sc/hydra/projects/schlea02a'
setenv RUMBA  'pmung@rumba.anbg.mssm.edu://home/pmung'
setenv TANGO  'pmung@tango.anbg.mssm.edu://home/pmung'
setenv BALLET 'pmung@ballet.anbg.mssm.edu://home/pmung'
setenv POINTE 'pmung@pointe.anbg.mssm.edu://home/pmung'
setenv SAMBA  'pmung@samba.anbg.mssm.edu://home/pmung'
setenv DISCO  'pmung@disco.anbg.mssm.edu://home/pmung'
setenv JETHRO 'pmung@jethro.anbg.mssm.edu://home/pmung'
setenv PILS   'pmung@pils-ext.phar.umich.edu://users/pmung'



#### Software Settings ####
setenv SOFT /home/software

## Mendeley 1.13.8 PDF searcher ##
alias mendeley $SOFT/mendeley-1.13.8/bin/mendeleydesktop

## Pymol 2.2.3 ##
setenv PYMOL_PATH $SOFT/pymol-223
alias pm2 $PYMOL_PATH/pymol

## Chimera 1.8 ##
setenv CHIM_PATH  $SOFT/chimera-1.8

## VMD 1.9.2 ##
setenv VMD_PATH $SOFT/vmd-1.9.2
setenv VMDPATH  $SOFT/vmd-1.9.2/vmd192

## Coot 0.8.9.1 ##
setenv COOT_PREFIX $SOFT/coot-0.8.9.1

## molBlocks ##
setenv MOLBLOCKS $SOFT/molblocks

## ChemAxon Marvin ##
#setenv MARVIN $SOFT/ChemAxon-150629/MarvinBeans
alias msketch MarvinSketch
alias mview MarvinView

## CytoScape 3.7.1 ##
setenv CYTOSC $SOFT/Cytoscape_v3.7.1

## LIGSIFT 1.0 ##
setenv LIGSF $SOFT/LIGSIFT

## DrugScoreX 0.89 ##
setenv DSX $SOFT/DrugScoreX/linux64
setenv DSX_POTENTIALS $SOFT/DrugScoreX/pdb_pot_0511
alias drugscore $DSX/dsx_linux_64.lnx
alias dsxmap $DSX/hotspotsX_linux_64.lnx

## TM-Score & TM-Align ##
#setenv TM $SOFT/ZhangLab

## Hollow 1.2 ##
#setenv HOLLOW $SOFT/hollow-1.2

## POVME ## 
setenv POVME $SOFT/povme-2.0
alias povme "python $POVME/POVME2.py "

## JalView 2.8.2 ##
setenv JALVIEW $SOFT/Jalview
alias jal $JALVIEW/Jalview

## T-Coffee Alignment ##
# installed as package
# sap mafft clustalo clustalw dialign-tx poa probcons muscle kalign 
# amap proda fsa blastTMalign mustang prank kalign
setenv BLASTDB /home/pmung/blast_db

## ConCoord 2.1.2 /tConCoord 1.0 ##
setenv CONCOORD $SOFT/concoord_2.1.2
setenv CONCOORDBIN $CONCOORD/bin
setenv CONCOORDLIB $CONCOORD/lib

## Scwrl 4.0 -- Side-Chain Optimzer ##
setenv SC_DIR $SOFT/scwrl4

## Amber 16 ##
setenv AMBERHOME $SOFT/amber18

## CPPTRAJ github ## 19.06.20
setenv CTRAJHOME $SOFT/ctraj
alias ctraj $CTRAJHOME/bin/cpptraj
alias ctraj.mpi $CTRAJHOME/bin/cpptraj.MPI
alias ctraj.omp $CTRAJHOME/bin/cpptraj.OMP

## Gromacs 5.0.5 ##
setenv GROMACSHOME $SOFT/gromacs-5.0.5		# OpenMP Enabled


## AutoDock 4.2.5.1 / AD_Vina 1.1.2 / MGLTools 1.5.6 ##
setenv MGL_PATH  $SOFT/mgltools-1.5.6
setenv AD4_PATH  $SOFT/autodock-4.2.6
setenv VINA_PATH $SOFT/AD_vina-1.1.2

setenv ADTUTIL   $MGL_PATH/MGLToolsPckgs/AutoDockTools/Utilities24


## MOE ##
#setenv MOE $SOFT/moe2015

## OpenEye ##
setenv OE_DIR  $SOFT/openeye
setenv OE_ARCH Ubuntu-10.04-x64:Ubuntu-12.04-x64:redhat-RHEL5-x64:Ubuntu-14.04-x64:Ubuntu-16.04-x64:Ubuntu-18.04
setenv OE_LICENSE $OE_DIR/oe_license.txt

## Schrodinger ##
setenv SCHRODINGER $SOFT/schrodinger2019-1
setenv SCHROD_LICENSE_FILE 43723@license.hpc.mssm.edu
#setenv SCHROD_LICENSE_FILE  27000@license.hpc.mssm.edu
setenv PYMOL4MAESTRO /home/software/pymol-223/pymol #$PYMOL_PATH
alias maestro 'setenv PYTHONPATH python3; $SCHRODINGER/maestro -NOSGL'

 # ligprep setting for ligand - 1 tautomer, 1 charge state # 2016-3+
#alias sch_ligprep "$SCHRODINGER/ligprep -i 2 -epik -We,-ph,7.2,-pht,0.3,-ms,1 -s 1 -r 1 -t 2 -bff 16 "  # pre 2015-3
alias sch_ligprep "setenv PYTHONPATH python3; $SCHRODINGER/ligprep -i 2 -epik -We,-ph,7.2,-pht,0.3,-ms,1 -s 1 -t 2 -bff 16 "

## MixMD ##
alias xplor "python ~/Dropbox/9_scripts/2_MD/mixMD/xplor_Normalize.py"


############################################################################

setenv SCRI /home/pmung/Dropbox/9_scripts
#echo "Use Python 2.7? ([t]/n): "
#set use_python2 = $<
#if ($use_python2 == 't' || $use_python2 == '') then
#  echo 'Using *Python2.7*'
  ## Python2.7 Paths to libraries ##
  ## MiniConda python2.7 ##
#  setenv CONDA /home/pmung/miniconda2/bin
#  source /home/pmung/miniconda2/etc/profile.d/conda.csh

#  setenv PYTHONPATH $SCRI/1_Docking/vina:$SCRI/3_program/python:$SCRI/3_program/pymol:$SCRI/3_program/modeller:$SCRI/3_program/rdkit:/usr/include/python2.7:/usr/lib/x86_64-linux-gnu:$SOFT/parmed-2.7.3:/usr/local/lib/python2.7/dist-packages
#:/usr/local/lib/python3.6/dist-packages:/usr/include/python3.6 #:/usr/local/lib/openbabel:$PYMOL_PATH/lib/python2.7:$PYMOL_PATH/lib/python2.7/lib-tk

#  setenv LD_LIBRARY_PATH $SCRI/3_program/python:/usr/local/lib:/usr/lib:/usr/local/lib/python2.7/dist-packages:$AMBERHOME/lib#:/usr/local/lib/python3.6/dist-packages #:/usr/local/lib/openbabel

#else
  ## Python3.7 Paths to libraries ##
  ## MiniConda python3 ##
#  echo 'Using *Python3.7*'
  alias python 'python3'

  setenv CONDA /home/pmung/miniconda3
  source /home/pmung/miniconda3/etc/profile.d/conda.csh
#  conda activate cdpy3


  setenv PYTHONPATH $SCRI/1_Docking/vina:$SCRI/3_program/python:$SCRI/3_program/pymol:$SCRI/3_program/modeller:$SCRI/3_program/rdkit#:/usr/include/python3.6:/usr/lib/x86_64-linux-gnu:$SOFT/parmed-2.7.3:/usr/local/lib/python3.6/dist-packages #:/usr/local/lib/openbabel #:$PYMOL_PATH/lib/python2.7:$PYMOL_PATH/lib/python2.7/lib-tk

  setenv LD_LIBRARY_PATH $SCRI/3_program/python:/usr/local/lib:/usr/lib:/usr/local/lib/openbabel:$AMBERHOME/lib#:/usr/local/lib/python3.6/dist-packages #:/usr/local/lib/python2.7/dist-packages #:$OBABEL/lib

#endif

############################################################################

setenv OB_INSTALLDIR /usr/local/lib:/usr/local/lib/openbabel:/usr/local/lib/python2.7/dist-packages
#:$RDBASE/lib:/usr/lib/x86_64-linux-gnu:/usr/include/python2.7:$PYMOL_PATH/lib/python2.7

## Modeller X.X ##
# installed as /usr/bin/modX.X
alias modeller 'mod9.20'


#### Set Paths ####
set path = ( $path ~pmung \
             /usr/bin  /usr/share /usr/local /usr/local/bin \
             /usr/lib /usr/lib32 /usr/lib64 /usr/local/lib \
             $VMD_PATH $COOT_PREFIX/bin \
             $AMBERHOME/bin $CTRAJHOME/bin $GROMACSHOME/bin \
             $MGL_PATH/bin $ADTUTIL $AD4_PATH $VINA_PATH/bin \
#             $MARVIN $MARVIN/bin \
             $OE_DIR/bin $SC_DIR \
	     $DSX/linux64 $POVME $LIGSF \
             $SCHRODINGER $SCHRODINGER/utilties \
             $MOLBLOCKS \
             $CONDA/bin \
#             $CONCOORD/bin $HOLLOW $TM \
#             $PYMOL_PATH $CHIM_PATH/bin $CYTOSC \
           )
source $AMBERHOME/amber.csh
#source $GROMACSHOME/bin/GMXRC
#source $SOFT/tCONCOORD-1.0/tCONCOORDRC.csh

## Mounting the NAS drive ## /etc/fstab
if ( ! -e /media/pmung/dlink1/backintime ) then
  echo "## Mount the NAS Drive -- sudo mount -a ##" 
  sudo mount -a
endif

if ! $?PATH setenv PATH '';
if "${PATH}" != '' setenv PATH "/home/pmung/perl5/bin:${PATH}";
if "${PATH}" == '' setenv PATH "/home/pmung/perl5/bin";
if ! $?PERL5LIB setenv PERL5LIB '';
if "${PERL5LIB}" != '' setenv PERL5LIB "/home/pmung/perl5/lib/perl5:${PERL5LIB}";
if "${PERL5LIB}" == '' setenv PERL5LIB "/home/pmung/perl5/lib/perl5";
if ! $?PERL_LOCAL_LIB_ROOT setenv PERL_LOCAL_LIB_ROOT '';
if "${PERL_LOCAL_LIB_ROOT}" != '' setenv PERL_LOCAL_LIB_ROOT "/home/pmung/perl5:${PERL_LOCAL_LIB_ROOT}";
if "${PERL_LOCAL_LIB_ROOT}" == '' setenv PERL_LOCAL_LIB_ROOT "/home/pmung/perl5";
if ! $?PERL_MB_OPT setenv PERL_MB_OPT '';
setenv PERL_MB_OPT "--install_base "\""/home/pmung/perl5"\""";
if ! $?PERL_MM_OPT setenv PERL_MM_OPT '';
setenv PERL_MM_OPT "INSTALL_BASE=/home/pmung/perl5";
